Repository Dev-FE-2/toy-project3-team3, pull requests merged in 2025-01, with the labels that each got.

#5 [Setting] 글로벌 스타일 추가
  .github/auto_assign.yml
  .github/workflow/action.yml
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
  public/assets/fonts/wotf/Pretendard-Bold.woff
  public/assets/fonts/wotf/Pretendard-Regular.woff
  public/assets/fonts/wotf/Pretendard-Thin.woff
  public/assets/fonts/wotf2/Pretendard-Bold.woff2
  public/assets/fonts/wotf2/Pretendard-Regular.woff2
  public/assets/fonts/wotf2/Pretendard-Thin.woff2
  src/components/layout/Layout.styles.ts
  src/components/layout/Layout.tsx
  src/styles/GlobalStyles.ts
  src/styles/designToken.css
  src/styles/fonts.css
  test-results/.last-run.json
  tsconfig.app.json
  tsconfig.node.json
Labels: Setting

#10 [Setting] design tokens 객체로 변경
  .gitignore
  src/components/layout/Layout.styles.ts
  src/components/layout/Layout.tsx
  src/design-tokens/colors.ts
  src/design-tokens/index.ts
  src/styles/GlobalStyles.ts
  src/styles/designToken.css
  src/styles/mediaQuery.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/types/example.ts
  src/types/style.ts
Labels: Refactor

#12 [Feature] 공통 컴포넌트 제작
  package-lock.json
  package.json
  prettier.config.js
  src/assets/img/profile/default_profile.webp
  src/assets/img/test/avatarTest.webp
  src/assets/img/test/tumbnailTest.webp
  src/components/common/Avatar/Avatar.styles.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Backward/Backward.styles.ts
  src/components/common/Backward/Backward.tsx
  src/components/common/Button/Button.styles.ts
  src/components/common/Button/Button.tsx
  src/components/common/Category/Category.styles.ts
  src/components/common/Category/Category.tsx
  src/components/common/DeferredLoader/DeferredLoader.styles.ts
  src/components/common/DeferredLoader/DeferredLoader.tsx
  src/components/common/EachPlaylist/EachPlaylist.styles.ts
  src/components/common/EachPlaylist/EachPlaylist.tsx
  src/components/common/ErrorFallback/ErrorFallback.styles.ts
  src/components/common/ErrorFallback/ErrorFallback.tsx
  src/components/common/Form/Form.styles.ts
  src/components/common/HashTag/HashTag.styles.ts
  src/components/common/HashTag/HashTag.tsx
  src/components/common/Icon/Icon.styles.ts
  src/components/common/Icon/Icon.tsx
  src/components/common/Input/Input.styles.ts
  src/components/common/Input/Input.tsx
  src/components/common/LikeAndSubscribe/LikeAndSubscribe.styles.ts
  src/components/common/LikeAndSubscribe/LikeAndSubscribe.tsx
  src/components/common/Search/Search.styles.ts
  src/components/common/Search/Search.tsx
  src/components/common/Select/Select.styles.ts
  src/components/common/Select/Select.tsx
  src/components/common/index.ts
  src/components/common/tabs/Tabs.styles.ts
  src/components/common/tabs/Tabs.tsx
  src/components/common/tabs/components/List.tsx
  src/components/common/tabs/components/Panel.tsx
  src/components/common/tabs/components/Trigger.tsx
  src/components/common/tabs/context/TabsContext.tsx
  src/components/layout/Layout.styles.ts
  src/components/layout/Layout.tsx
  src/constants/common.ts
  src/constants/index.ts
  src/main.tsx
  src/styles/GlobalStyles.ts
  src/styles/mediaQuery.ts
  src/styles/theme.ts
  src/types/common.ts
  src/utils/createOptions.ts
  src/utils/example.ts
  src/utils/index.ts
Labels: Feature

#16 [Refactor] 공통 컴포넌트 접근성 개선
  src/components/common/Avatar/Avatar.styles.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Button/Button.styles.ts
  src/components/common/Button/Button.tsx
  src/components/common/Category/Category.tsx
  src/components/common/DeferredLoader/DeferredLoader.tsx
  src/components/common/EachPlaylist/EachPlaylist.tsx
  src/components/common/ErrorFallback/ErrorFallback.tsx
  src/components/common/HashTag/HashTag.tsx
  src/components/common/Icon/Icon.tsx
  src/components/common/Input/Input.styles.ts
  src/components/common/Input/Input.tsx
  src/components/common/LikeAndSubscribe/LikeAndSubscribe.tsx
  src/components/common/Search/Search.tsx
  src/components/common/Select/Select.tsx
  src/components/common/tabs/Tabs.styles.ts
  src/components/common/tabs/Tabs.tsx
  src/components/common/tabs/components/List.tsx
  src/components/common/tabs/components/Panel.tsx
  src/components/common/tabs/components/Trigger.tsx
  src/components/common/tabs/context/TabsContext.tsx
  src/styles/mediaQuery.ts
  src/types/common.ts
  src/types/index.ts
Labels: Refactor

#14 [Setting] supabase 기초 세팅
  package-lock.json
  package.json
  src/apis/supabase.ts
  src/main.tsx
  src/supabase/SupabaseContext.tsx
  src/types/database.types.ts
Labels: Setting

#20 [Fix] input 컴포넌트 오류 해결
  src/components/common/Form/Form.styles.ts
  src/components/common/Input/Input.styles.ts
  src/components/common/Input/Input.tsx
  src/components/common/index.ts
  src/constants/index.ts
  src/constants/user.ts
  src/main.tsx
  src/pages/SignUpPage/SignUpPage.styles.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/schemas/user/baseUserSchema.ts
  src/schemas/user/editProfileSchema.ts
  src/schemas/user/signInSchema.ts
  src/schemas/user/signUpSchema.ts
  src/types/common.ts
Labels: BugFix, Feature

#18 [Feature] errorBoundary, suspense 추가
  src/apis/example.ts
  src/apis/index.ts
  src/apis/react-query.ts
  src/components/common/ErrorFallback/ErrorFallback.styles.ts
  src/components/common/ErrorFallback/ErrorFallback.tsx
  src/components/index.ts
  src/components/layout/Layout.tsx
  src/main.tsx
  src/pages/NotFoundPage/NotFoundPage.styles.ts
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/routes/router.tsx
Labels: Feature

#23 [feature] supabase 데이터 CRUD를 위한 기능 구현
  package-lock.json
  package.json
  src/apis/supabase.ts
  src/constants/endpoint.ts
  src/constants/index.ts
  src/constants/queryKeys.ts
  src/contexts/SupabaseContext.ts
  src/contexts/SupabaseProvider.tsx
  src/hooks/index.ts
  src/hooks/mutations/index.ts
  src/hooks/mutations/useSignIn.ts
  src/hooks/mutations/useSignUp.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useFetchPlayList.ts
  src/hooks/queries/useFetchUser.ts
  src/hooks/useComment.ts
  src/hooks/useFollow.ts
  src/hooks/useHashtag.ts
  src/hooks/useLike.ts
  src/hooks/usePlaylist.ts
  src/hooks/usePlaylistVideo.ts
  src/hooks/useSubscribe.ts
  src/hooks/useSupabase.ts
  src/hooks/useSupabaseCrud.ts
  src/hooks/useUser.ts
  src/main.tsx
  src/services/index.ts
  src/services/supabaseService.ts
  src/types/database.types.ts
  src/types/index.ts
  src/types/supabaseCrud.ts
Labels: Feature

#31 [Feature] supabase의 CATEGORY 테이블 데이터를 페칭하는 커스텀 훅 구현
  src/constants/endpoint.ts
  src/constants/queryKeys.ts
  src/hooks/useCategory.ts
  src/types/database.types.ts
Labels: Feature

#28 [Feature] 헤더 스크롤시 숨김 처리 기능 추가
  src/components/common/index.ts
  src/components/layout/Header/Header.styles.ts
  src/components/layout/Header/Header.tsx
  src/components/layout/Layout.styles.ts
  src/components/layout/Layout.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: Feature

#34 [BugFix] 하단 Nav바 경로 버그
  src/components/common/index.ts
Labels: BugFix

#41 [BugFix] modal/alert 폴더명 소문자 대문자 충돌 해결
  src/components/common/modal/alert/Alert.styles.ts
  src/components/common/modal/alert/Alert.tsx
  src/components/common/modal/alert/context/AlertContext.ts
  src/components/common/modal/alert/context/AlertProvider.tsx
  src/components/common/modal/alert/index.ts
Labels: BugFix

#39 [BugFix] usefollow 내부 쿼리 키 수정 및 querykeys.ts 파일에 새로운 쿼리 키 추가 (#36)
  src/constants/queryKeys.ts
  src/hooks/useFollow.ts
Labels: BugFix

#49 [Feature] 마이 페이지 메뉴 바
  .husky/pre-push
  package-lock.json
  src/atoms/index.ts
  src/atoms/menuBarAtom.ts
  src/components/common/index.ts
  src/components/common/tabs/components/Trigger.tsx
  src/components/index.ts
  src/components/layout/Header/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Nav/Nav.tsx
  src/components/user/User.styles.ts
  src/components/user/User.tsx
  src/components/user/index.ts
  src/components/user/menuBar/MenuBar.styles.ts
  src/components/user/menuBar/MenuBar.tsx
  src/hooks/ui/useShowHeader.ts
  src/pages/MyFollowingPage/MyFollowingPage.tsx
  src/pages/UserFollowPage/UserFollowPage.tsx
  src/pages/UserPage/PostTab.tsx
  src/pages/UserPage/SubscripbeTab.tsx
  src/pages/UserPage/UserPage.tsx
  src/types/common.ts
  src/types/database.types.ts
  toy-project-team3-1.zip
Labels: Feature

#56 [Feature] 플레이리스트 컴포넌트 구현
  package-lock.json
  package.json
  src/components/common/Icon/Icon.styles.ts
  src/components/common/Icon/Icon.tsx
  src/components/index.ts
  src/components/playlist/common/BottomSheet/BottomSheet.styles.ts
  src/components/playlist/common/BottomSheet/BottomSheet.tsx
  src/components/playlist/common/CommentItems/CommentItems.styles.ts
  src/components/playlist/common/CommentItems/CommentItems.tsx
  src/components/playlist/common/UserProfile/UserProfile.styles.ts
  src/components/playlist/common/UserProfile/UserProfile.tsx
  src/components/playlist/common/VideoItems/VideoItems.styles.ts
  src/components/playlist/common/VideoItems/VideoItems.tsx
  src/components/playlist/common/index.ts
  src/components/playlist/play-list-edit/EditContents/ContentsHashtag/ContentsHashtag.styles.ts
  src/components/playlist/play-list-edit/EditContents/ContentsHashtag/ContentsHashtag.tsx
  src/components/playlist/play-list-edit/EditContents/EditContents.styles.ts
  src/components/playlist/play-list-edit/EditContents/EditContents.tsx
  src/components/playlist/play-list-edit/EditPlayList/EditPlayList.tsx
  src/components/playlist/play-list-edit/EditPlayList/VideoSearchBar/VideoSearchBar.styles.ts
  src/components/playlist/play-list-edit/EditPlayList/VideoSearchBar/VideoSearchBar.tsx
  src/components/playlist/play-list-edit/EditThumbnail/EditThumbnail.styles.ts
  src/components/playlist/play-list-edit/EditThumbnail/EditThumbnail.tsx
  src/components/playlist/play-list-edit/index.ts
  src/components/playlist/playlist/PlaylistContents/CommentList/CommentList.styles.ts
  src/components/playlist/playlist/PlaylistContents/CommentList/CommentList.tsx
  src/components/playlist/playlist/PlaylistContents/CommentList/CommentReply/CommentReply.styles.ts
  src/components/playlist/playlist/PlaylistContents/CommentList/CommentReply/CommentReply.tsx
  src/components/playlist/playlist/PlaylistContents/ContentsInfo/ContentsInfo.styles.ts
  src/components/playlist/playlist/PlaylistContents/ContentsInfo/ContentsInfo.tsx
  src/components/playlist/playlist/PlaylistContents/PlaylistContents.styles.ts
  src/components/playlist/playlist/PlaylistContents/PlaylistContents.tsx
  src/components/playlist/playlist/PlaylistContents/VideoList/VideoList.styles.ts
  src/components/playlist/playlist/PlaylistContents/VideoList/VideoList.tsx
  src/components/playlist/playlist/VideoPlayer/VideoPlayer.styles.ts
  src/components/playlist/playlist/VideoPlayer/VideoPlayer.tsx
  src/components/playlist/playlist/index.ts
  src/constants/endpoint.ts
  src/constants/queryKeys.ts
  src/constants/routes.ts
  src/hooks/index.ts
  src/hooks/play-list/index.ts
  src/hooks/play-list/useLikeHandling.ts
  src/hooks/play-list/useOptimisticFollowHandling.ts
  src/hooks/play-list/useOptimisticLikeToComment.ts
  src/hooks/play-list/useSubscribeHandling.ts
  src/hooks/useComment.ts
  src/hooks/useFollow.ts
  src/hooks/useLike.ts
  src/hooks/useSubscribe.ts
  src/pages/PlayListEditPage/PlayListEditPage.styles.ts
  src/pages/PlayListEditPage/PlayListEditPage.tsx
  src/pages/PlayListPage/PlayListPage.tsx
  src/pages/index.ts
  src/types/common.ts
  src/types/playlist.ts
  src/utils/index.ts
  src/utils/playlist/getRelativeTime.ts
  src/utils/playlist/index.ts
Labels: Feature

#46 [feature] 검색페이지 구현
  src/components/common/Search/Search.styles.ts
  src/components/common/Search/Search.tsx
  src/pages/SearchPage/SearchPage.styles.ts
  src/pages/SearchPage/SearchPage.tsx
  src/services/getEachPlayListInfo.ts
  src/types/common.ts
  src/types/database.types.ts
Labels: Feature

#53 [Feature] 마이페이지 컴포넌트 구현
  src/pages/UserPage/PostTab.tsx
  src/pages/UserPage/UserPage.styles.ts
  src/pages/UserPage/UserPage.tsx
Labels: Feature

#54 [Feature] 유저 팔로우/팔로잉 컴포넌트 페이지 구현
  src/pages/UserFollowPage/UserFollowPage.styles.ts
  src/pages/UserFollowPage/UserFollowPage.tsx
Labels: Feature

#55 [Feature] 팔로잉하는 유저의 플레이리스트 컴포넌트 페이지 구현
  src/pages/MyFollowingPage/MyFollowingPage.styles.ts
  src/pages/MyFollowingPage/MyFollowingPage.tsx
Labels: Feature

#44 [feature] 메인페이지 구현
  src/components/common/Category/CategoryContext.tsx
  src/components/common/Category/CategoryProvider.tsx
  src/components/layout/Header/Header.styles.ts
  src/components/layout/Header/Header.tsx
  src/components/layout/Layout.tsx
  src/constants/endpoint.ts
  src/hooks/useCategory.ts
  src/hooks/usePlaylist.ts
  src/pages/HomePage/HomePage.styles.ts
  src/pages/HomePage/HomePage.tsx
  src/types/common.ts
Labels: Feature

#59 [BugFix] 하단 네비게이션의 경로 오류를 수정합니다
  src/components/layout/Nav/Nav.tsx
Labels: Feature

#64 [Feature] 사용자 검색 화면에서 사용자를 팔로우/언팔로우 할 수 있도록 기능 추가
  src/pages/SearchPage/SearchPage.tsx
Labels: Feature

#60 [BugFix] 플레이리스트 클릭시 상세페이지 링크 연결 에러
  src/pages/HomePage/HomePage.tsx
  src/pages/SearchPage/SearchPage.tsx
Labels: BugFix

#37 [feature] 알림페이지 구현
  src/components/layout/Header/Header.tsx
  src/constants/endpoint.ts
  src/hooks/useAlertType.ts
  src/hooks/useAlerts.ts
  src/pages/AlertPage/AlertPage.styles.ts
  src/pages/AlertPage/AlertPage.tsx
  src/types/database.types.ts
Labels: Feature
